// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using TechVault.Infrastructure.Persistence;

#nullable disable

namespace TechVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TechVaultDbContext))]
    partial class TechVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechVault.Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands", null, t =>
                        {
                            t.HasCheckConstraint("CK_Brands_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Brands_Slug", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_Categories_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Categories_Parent", "\"ParentCategoryId\" IS NULL OR \"ParentCategoryId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_Categories_Slug", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Comparisons.ComparisonGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ComparisonGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_ComparisonGroups_Key", "\"Key\" ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_ComparisonGroups_Name", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComparisonGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DepthMm")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<DateOnly?>("DiscontinuedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("HeightMm")
                        .HasColumnType("numeric");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasDefaultValueSql("''::tsvector");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightGrams")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WidthMm")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<List<string>>("_aliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("Aliases")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComparisonGroupId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ReleaseYear", "ReleaseDate", "Slug")
                        .HasDatabaseName("IX_Devices_Timeline")
                        .HasFilter("\"Status\" = 1 AND \"ReleaseYear\" IS NOT NULL");

                    b.ToTable("Devices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Devices_Aliases", "cardinality(\"Aliases\") <= 20 AND array_position(\"Aliases\", NULL) IS NULL");

                            t.HasCheckConstraint("CK_Devices_DiscontinuedDate", "\"DiscontinuedDate\" IS NULL OR\n((\"ReleaseDate\" IS NULL OR \"DiscontinuedDate\" >= \"ReleaseDate\")\n AND (\"ReleaseYear\" IS NULL OR EXTRACT(YEAR FROM \"DiscontinuedDate\") >= \"ReleaseYear\"))");

                            t.HasCheckConstraint("CK_Devices_ModelNumber", "\"ModelNumber\" IS NULL OR length(btrim(\"ModelNumber\")) > 0");

                            t.HasCheckConstraint("CK_Devices_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Devices_PhysicalMeasurements", "(\"HeightMm\" IS NULL OR \"HeightMm\" > 0) AND (\"WidthMm\" IS NULL OR \"WidthMm\" > 0)\nAND (\"DepthMm\" IS NULL OR \"DepthMm\" > 0) AND (\"WeightGrams\" IS NULL OR \"WeightGrams\" > 0)");

                            t.HasCheckConstraint("CK_Devices_Publication", "(\"Status\" <> 1 OR (\"PublishedAt\" IS NOT NULL\n    AND length(btrim(\"ShortDescription\")) > 0 AND length(btrim(\"Description\")) > 0\n    AND length(btrim(\"History\")) > 0 AND length(btrim(\"SeoTitle\")) > 0\n    AND length(btrim(\"SeoDescription\")) > 0))\nAND (\"Status\" = 1 OR \"PublishedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_Devices_ReleaseDate", "\"ReleaseDate\" IS NULL OR\n(\"ReleaseYear\" IS NOT NULL AND EXTRACT(YEAR FROM \"ReleaseDate\") = \"ReleaseYear\")");

                            t.HasCheckConstraint("CK_Devices_ReleaseYear", "\"ReleaseYear\" IS NULL OR \"ReleaseYear\" BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("CK_Devices_Slug", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Devices_Status", "\"Status\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Specifications.DeviceSpecification", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.HasKey("DeviceId", "DefinitionId");

                    b.HasIndex("DefinitionId", "DataType");

                    b.ToTable("DeviceSpecifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeviceSpecifications_TypedValue", "(\"DataType\" = 1 AND \"ValueText\" IS NOT NULL AND length(btrim(\"ValueText\")) > 0\n    AND \"ValueNumber\" IS NULL AND \"ValueBoolean\" IS NULL AND \"ValueDate\" IS NULL)\nOR (\"DataType\" = 2 AND \"ValueNumber\" IS NOT NULL\n    AND \"ValueText\" IS NULL AND \"ValueBoolean\" IS NULL AND \"ValueDate\" IS NULL)\nOR (\"DataType\" = 3 AND \"ValueBoolean\" IS NOT NULL\n    AND \"ValueText\" IS NULL AND \"ValueNumber\" IS NULL AND \"ValueDate\" IS NULL)\nOR (\"DataType\" = 4 AND \"ValueDate\" IS NOT NULL\n    AND \"ValueText\" IS NULL AND \"ValueNumber\" IS NULL AND \"ValueBoolean\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Specifications.SpecificationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComparable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SpecificationDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SpecificationDefinitions_DataType", "\"DataType\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_SpecificationDefinitions_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_SpecificationDefinitions_Key", "\"Key\" ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_SpecificationDefinitions_Name", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Specifications.SpecificationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SpecificationGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_SpecificationGroups_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_SpecificationGroups_Key", "\"Key\" ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_SpecificationGroups_Name", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("TechVault.Domain.Categories.Category", b =>
                {
                    b.HasOne("TechVault.Domain.Categories.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TechVault.Domain.Devices.Device", b =>
                {
                    b.HasOne("TechVault.Domain.Brands.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechVault.Domain.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechVault.Domain.Comparisons.ComparisonGroup", "ComparisonGroup")
                        .WithMany()
                        .HasForeignKey("ComparisonGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("ComparisonGroup");
                });

            modelBuilder.Entity("TechVault.Domain.Specifications.DeviceSpecification", b =>
                {
                    b.HasOne("TechVault.Domain.Devices.Device", null)
                        .WithMany("Specifications")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechVault.Domain.Specifications.SpecificationDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId", "DataType")
                        .HasPrincipalKey("Id", "DataType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("TechVault.Domain.Specifications.SpecificationDefinition", b =>
                {
                    b.HasOne("TechVault.Domain.Specifications.SpecificationGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TechVault.Domain.Devices.Device", b =>
                {
                    b.Navigation("Specifications");
                });
#pragma warning restore 612, 618
        }
    }
}
